### PR TITLE
Add Clang 5.0 static analysis with scan-build

### PR DESCRIPTION
**Pull request by tklengyel**

### CODE REVIEW

**Comment by rianquinn** [comment]
since we already do static analysis with clang, I would prefer to simply update that test to 5.0 as Clang Tidy is finding a lot more things than scan-build is (it only does the static analysis part), which means all it's doing is slowing down that particular test. Thoughts?

**Comment by tklengyel** [comment]
I guess since scan-build ships with clang by default it's a useful option in case you don't want to install extra stuff. Also my impression with clang tidy was that it won't work for C projects?

**Comment by rianquinn** [comment]
Works fine for C projects. I'm fine with showing examples of how to set it up, but I wouldn't add it to the default for clang 5.0

**Comment by tklengyel** [comment]
Adding a separate clang 5.0 build would make sense. I'm looking for an easy way to setup clang tidy for an autotools project and there is just not much info about it out there. :/

**Comment by rianquinn** [comment]
Yeah, all you need to do is get autotools to spit out a JSON database. I would start with this project as we used to use this and it worked great: https://github.com/rizsotto/Bear

**Comment by rianquinn** [comment]
Once you have a database, you can run Clang-Tidy without issue (assuming clang was used as the compiler of course).

**Pull request closed without merging**
